# This is a basic workflow to help you get started with Actions
name: Testing
# Controls when the action will run. 
on:
  push: #Triggers the workflow on push or pull request events
  workflow_dispatch: # Allows manual trigger

jobs:
  test-matlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checks-out repository under $GITHUB_WORKSPACE
      # Install MATLAB
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1        
      # Runs test command
      - name: Run Testscript
        uses: matlab-actions/run-command@v1
        with:
          command: cd unitTest; matRad_runTests
